# docker-compose.yml

services:
  api:
    image: citatech/fastapi-book-project:latest
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000" 
    environment:
      - ENVIRONMENT=production
      - DEBUG=1
    restart: always

  nginx:
    image: nginx:1.19
    container_name: nginx
    ports:
      - "80:80"  
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    restart: always